#生产环境
server:
  port: 8011
spring:
  devtools:
    add-properties: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:mysql://1.14.96.5:3306/linktree?serverTimezone=UTC&characterEncoding=utf-8
    username: linktree
    password: dl2002123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: qq2002123
    jedis:
      pool:
          max-active: 8 #连接池最大连接数（使用负值表示没有限制）
          max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8  #连接池中的最大空闲连接
          min-idle: 0 #连接池中的最小空闲连接
      lettuce:
        shutdown-timeout: 100ms #关闭超时时间，默认值100ms
#自定义全局变量
global:
  jwt:
    key: emqqtxea  #jwt得加密密匙
#  mqtt:
#    clientid: testcqaevefffgqe
#    host: tcp://0.0.0.0:1883
#    password: qq2002123
#    timeout: 1000
#    keepalive: 10
config:
  evn:
    name: 85